### ISSUE TITLE
在1.19Fabric客户端中闪退

### ISSUE THREAD

**Issue by LsrlYrsc** [Nova-Committee/PetPhrase-Client#2]
你好开发者，我很高兴有这个模组喵(
但是他在1.19的fabric端上闪退，我尝试了新端插入，也是闪退，我会附上崩溃目录，希望能解决，谢谢喵!ew
[latest.log](https://github.com/Nova-Committee/PetPhrase-Client/files/9307305/latest.log)
e

**Comment by VulpesStella** [comment]
The 1.19.X jar was checked to be running all good on 1.19.1. I thought it should be compatible with 1.19 as well, but actually it doesn't.

**Comment by LsrlYrsc** [comment]
所以你可以制作一个适配1.19的模组吗？我知道我说这句话有点不合适（麻烦），但是我1.19.1的更新内容让我感觉有点不适，谢谢理解喵

**Comment by LsrlYrsc** [comment]
我在1.19版本花了很多时间在mod上面,但我主要喜欢你这个模组，如果不能做出适配1.19的模组的话，我仍然会升级到你适配的版本，谢谢喵

**Comment by VulpesStella** [comment]
我吃完饭回来做（
1.19.1确实不太行，但还是习惯性地更了

**Comment by LsrlYrsc** [comment]
那真的太谢谢你了！喵喵喵！ewe

**Comment by VulpesStella** [comment]
新版本已在百科下载页上传~
