### ISSUE TITLE
Forge-1.18.2，找不出崩溃原因

### ISSUE THREAD

**Issue by qznfbnj** [Nova-Committee/PetPhrase-Client#4]
加到bmc-forge-1.18.2-v19中，在世界地图新建路径点，将路径点发送到聊天栏，然后点击聊天栏中的路径点就会崩溃。
PCL2 启动器说和 FPSReducer/PetPhrase 有关，但是把 FPSReducer、PetPhrase、XaeroMini/WorldMap 装一起崩溃消失。
排查了两天了找不出原因，排查到现在这个时间点出现了一种奇怪的现象：mod 数量=193时，拿掉任意一个除了 FPSReducer/PetPhrase 外的 mod，崩溃就会消失，给我整麻了。
[debug.log](https://gist.github.com/qznfbnj/b8f9ac7d078517c5fcd90e28a9d3603e)
[crash-2023-04-14_18.23.56-client.txt](https://gist.github.com/qznfbnj/07fac2c0fc6440a327644823ec755174)

**Comment by VulpesStella** [comment]
确实是PetPhrase的问题，待会修

**Comment by VulpesStella** [comment]
工作区有点问题，我改完后直接用action构建了，你看看能不能用 :D
[下载](https://github.com/Nova-Committee/PetPhrase-Client/suites/12290150208/artifacts/651146603)

**Comment by qznfbnj** [comment]
哦哦，点击聊天栏中的路径点不会崩溃了，那我先关闭了，如果发现什么问题再重新打开
![image](https://user-images.githubusercontent.com/100760086/232672272-053ac1d3-b51c-441b-bea4-bab89723f4c0.png)
